<!DOCTYPE html>
<html lang="uk">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <title>Medical Card</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 14px;
        }

        .header {
            text-align: center;
            font-size: 24px;
            margin-bottom: 20px;
        }

        .content {
            margin: 20px 0;
        }

        .label {
            font-weight: bold;
        }

        .footer {
            text-align: center;
            font-size: 10px;
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Medical Card</h1>
        <p>Patient: {{ $patient->user->first_name }} {{ $patient->user->last_name }}</p>
    </div>

    <div class="content">
        <p><span class="label">Wight:</span> {{ $weight }}</p>
        <p><span class="label">Height:</span> {{ $height }}</p>
        <p><span class="label">Blood type:</span> {{ $blood_type }}</p>
        <p><span class="label">Blood Pressure:</span> {{ $blood_pressure }}</p>
    </div>

    <div class="footer">
        <p>Generated by: {{ auth()->user()->first_name . ' ' . auth()->user()->last_name }}</p>
        <p>Date: {{ now()->toDateString() }}</p>
    </div>
</body>

</html>
